### PR TITLE
avoid crash when zooming to project site

### LINKED ISSUE #1138: Error: viewport-mercator-project: assertion failed.
Sentry Issue: [APP-20-NEXT-1SF](https://sentry.io/organizations/plant-for-the-planet/issues/2260009482/?referrer=github_integration)

```
Error: viewport-mercator-project: assertion failed.
  at r (/_next/static/chunks/pages/_app-5e40073a52cb7e36db4a.js:1:4006096)
  at a (/_next/static/chunks/pages/_app-5e40073a52cb7e36db4a.js:1:4006965)
  at t.value (/_next/static/chunks/pages/_app-5e40073a52cb7e36db4a.js:1:4015662)
  at Oe (/_next/static/chunks/pages/_app-5e40073a52cb7e36db4a.js:1:2989481)
  at None (/_next/static/chunks/pages/_app-5e40073a52cb7e36db4a.js:1:2992758)
...
(7 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by norbertschuler**
Fix #1138

Changes in this pull request:
- added exception for not using bigger padding for mobile devices if in landscape mode
- added check if viewport.width and viewport.height exists and do not zoom without these values

Unfortunately window.orientation or screen.orientation are not available in all browser, e.g. Safari on MacOS.

### CODE REVIEW

File: src/utils/maps/zoomToProjectSite.ts [hunk 1]
```diff
@@ -6,42 +6,60 @@ export default function zoomToProjectSite(
...
+    setViewPort(newViewport);
+    setSiteViewPort({center:[longitude,latitude],zoom:defaultZoom});  
+  } else {
+    const newViewport = {
+      ...viewport,
+      height: window.innerHeight,
+      width: window.innerWidth,
+    };
+    setViewPort(newViewport);
   }
```
Comment (norbertschuler) [inline src/utils/maps/zoomToProjectSite.ts:64]: This idea does not work. If loading the project in a background tab the map is just showing the location without zooming in.

**Comment by harshvitra** [comment]
I don't see this issue in dev.pp.eco and the other conditions you mentioned in the #1138 

Screenshot 2021-09-02 at 4 30 44 PM

But this branch also works well, so we can take the benefit of the doubt and merge this

**Review by harshvitra — APPROVED** [review]
