### PR TITLE
My Trees Fixes

### LINKED ISSUE #539: Change from TPO profile to own profile does not work
**Describe the bug**
If you visit https://beta.plant-for-the-planet.org/t/plant-for-the-planet and click on "me" to change to your own profile, the URL changes e.g. to https://beta.plant-for-the-planet.org/t/norbert-schuler, but the page does not change.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to https://beta.plant-for-the-planet.org/t/plant-for-the-planet
2. Click on 'Me'
3. See error

**Expected behavior**
Change to own profile.

**What actually happens**
Changes browser URL, but not the page.

**Screenshots**
Bildschirmfoto 2020-12-02 um 16 12 07

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome

### PR DESCRIPTION
**Pull request by sarveshpro**
Fixes #539

Changes in this pull request:
- My trees are now refreshed when you come back to me from another profile
- "My trees" when logged in "Name's Trees" for public profiles
- changed text in register trees for drawing a polygon
- removed unused code

### CODE REVIEW

File: src/features/user/UserProfile/components/MyTrees/MyTrees.tsx [hunk 1]
```diff
@@ -43,7 +47,11 @@ export default function MyTrees({ profile }: Props): ReactElement {
       Array.isArray(contributions) &&
       contributions.length !== 0 ? (
         <div className={styles.myTreesSection}>
-          <div className={styles.myTreesTitle}>{t('me:myForest')}</div>
+          <div className={styles.myTreesTitle}>
+            {authenticatedType === 'private'
+              ? t('me:myForest')
+              : t('me:nameForest', { name: profile.displayName })}
```
Comment (norbertschuler) [inline src/features/user/UserProfile/components/MyTrees/MyTrees.tsx:53]: If I login as a TPO is does not say `My Forest`, but `<Name>'s Forest` looking at the own profile. Is that ok?

File: public/static/locales/en/me.json [hunk 2]
```diff
@@ -12,16 +12,16 @@
   "close": "Close",
   "support": "Support",
   "addTarget": "Add Target",
-  "noOfTrees": "Number of trees",
+  "noOfTrees": "How many trees?",
   "datePlanted": "Date Planted",
   "speciesIsRequired": "Species is required",
   "treeSpecies": "Tree Species",
-  "drawPolygon": "Please draw a polygon to locate your trees",
+  "drawPolygon": "Please draw the area where you planted the trees. Click on the first location again when you are done",
```
Comment (norbertschuler) [inline public/static/locales/en/me.json:19]: I cannot yet see this resource as multiple tree registration does not yet work for me. Is that correct that multiple tree registration does not yet work?

Comment (sarveshpro) [reply public/static/locales/en/me.json:19]: If you enter more than 25 trees it will ask you to draw a polygon

File: src/features/user/UserProfile/components/MyTrees/MyTrees.tsx (hunk 1 above)
Comment (norbertschuler) [reply src/features/user/UserProfile/components/MyTrees/MyTrees.tsx:53]: Fixed it with https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/562/commits/4c1b9500a6913bfcfecc85b87da40ca3a0878e6c

Comment (sarveshpro) [reply src/features/user/UserProfile/components/MyTrees/MyTrees.tsx:53]: No, but I can see you fixed it :)

File: public/static/locales/en/me.json (hunk 2 above)
Comment (norbertschuler) [reply public/static/locales/en/me.json:19]: It never came to my mind to test with higher numbers ;-)

**Review by norbertschuler — APPROVED** [review]
LGFM
