### PR TITLE
load user info from server on login

### LINKED ISSUE #720: Wrong userInfo after login with Auth0
**Describe the bug**
Sometimes a user got logged out, but in the browser's localStorage the `userInfo` value is still stored. After the user logged in again with Auth0 with another account, this value of `userInfo` in the localStorage does not get updated, so e.g. the Navbar component is still showing the wrong user image.

**Is it on a Production or Development Build?**
production.

**To Reproduce**
1. Find a situation where you are logged out without doing it yourself (as then the userInfo value is deleted)
2. Login again
3. See error

**Expected behavior**
Update the `userInfo` value with an API call everytime a new login with Auth0 is done.

**What actually happens**
`userInfo` is not updated.

**Screenshots**
Screen Shot 2020-12-23 at 1 38 52 PM

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome

### PR DESCRIPTION
**Pull request by norbertschuler**
Fixes #720

Changes in this pull request:
- remove userInfo in callback from Auth0 to force new load from API <- this is the fix
- only more use one place to handle 'userInfo' in localStorage
- changed duplicate getUserInfo function name
- adding missing ui_locales to loginWithRedirect

### CODE REVIEW

File: pages/_app.tsx [hunk 1]
```diff
@@ -36,6 +37,7 @@ if (process.env.NEXT_PUBLIC_SENTRY_DSN) {
 }
 
 const onRedirectCallback = (appState) => {
+  removeLocalUserInfo();
```
Comment (norbertschuler) [inline pages/_app.tsx:40]: This is the fix, the rest of the PR is refactoring work.

**Review by harshvitra — APPROVED** [review]
