### PR TITLE
Solved Image uploading error in manage projects

### LINKED ISSUE #690: Error when uploading image for project
**Describe the bug**
If you want to upload an image to a project, the image got uploaded, but I see this error:

```
Unhandled Runtime Error
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLDivElement'
    |     property '__reactFiber$7pk36w60de9' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle

Source
src/utils/apiRequests/api.ts (95:17) @ _callee6$

  93 | const res = await fetch(process.env.API_ENDPOINT + url, {
  94 |     method: 'POST',
> 95 |     body: JSON.stringify(data),
     |               ^
  96 |     headers: {
  97 |         'Content-Type': 'application/json',
  98 |         'tenant-key': `${process.env.TENANTID}`,
Call Stack
postAuthenticatedRequest
src/utils/apiRequests/api.ts (91:0)
uploadPhotos
src/features/user/ManageProjects/components/ProjectMedia.tsx (52:28)
```

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to Manage Projects
2. Open or create a projects
3. Upload an image in the section for project media files

**Expected behavior**
Do not raise an error.

**Screenshots**
Bildschirmfoto 2020-12-21 um 11 12 13

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome

**Additional context**
This is a minor issue as the upload works anyway.

### PR DESCRIPTION
**Pull request by rishsingh07**
fixed #690

### CODE REVIEW

File: src/features/user/ManageProjects/components/ProjectMedia.tsx [hunk 1]
```diff
@@ -67,7 +68,7 @@ export default function ProjectMedia({ handleBack, token, handleNext, projectDet
         }
 
       }
-
+      console.log("hello", uploadPhotos);
```
Comment (harshvitra) [inline src/features/user/ManageProjects/components/ProjectMedia.tsx:71]: Remove console

File: src/features/user/ManageProjects/components/ProjectMedia.tsx [hunk 2]
```diff
@@ -278,7 +279,7 @@ export default function ProjectMedia({ handleBack, token, handleNext, projectDet
           <div className={styles.formFieldLarge} {...getRootProps()}>
             <label htmlFor="upload" className={styles.fileUploadContainer}>
               <AnimatedButton
-                onClick={uploadPhotos}
+                // onClick={uploadPhotos}
```
Comment (harshvitra) [inline src/features/user/ManageProjects/components/ProjectMedia.tsx:282]: Remove this too

**Review by harshvitra — CHANGES_REQUESTED** [review]

**Review by harshvitra — APPROVED** [review]
