### PR TITLE
fix missing translations

### LINKED ISSUE #1244: Translations missing in TreeMapper
The red marked data is not translated in the UI:

Bildschirmfoto 2021-09-09 um 16 53 26

### PR DESCRIPTION
**Pull request by sarveshpro**
Fixes #1244

### CODE REVIEW

File: src/features/user/TreeMapper/components/PlantLocationPage.tsx [hunk 1]
```diff
@@ -135,7 +135,7 @@ export function LocationDetails({
           if (element.coordinates?.[0]) {
             images.push({
               image: element.coordinates[0].image,
-              description: `${t('sampleTree')} ${
+              description: `${t('maps:sampleTree')} ${
```
Comment (norbertschuler) [inline src/features/user/TreeMapper/components/PlantLocationPage.tsx:138]: There is another `${t('sampleTree')}` below you have not changed!

File: src/features/user/TreeMapper/components/PlantLocationPage.tsx [hunk 2]
```diff
@@ -174,11 +174,11 @@ export function LocationDetails({
       <div className={styles.details}>
         <div className={styles.singleDetail}>
           <p className={styles.title}>{t('captureMode')}</p>
-          <div className={styles.value}>{location.captureMode}</div>
+          <div className={styles.value}>{t(location.captureMode)}</div>
```
Comment (norbertschuler) [inline src/features/user/TreeMapper/components/PlantLocationPage.tsx:177]: There ain't any resources named `location.captureMode` or `location.captureStatus` yet, are there?

File: src/features/user/TreeMapper/components/PlantLocationPage.tsx [hunk 3]
```diff
@@ -250,7 +250,7 @@ export function LocationDetails({
                       {species.treeCount}{' '}
                       {species.scientificName
                         ? species.scientificName
-                        : species.otherSpecies}
+                        : species.otherSpecies?species.otherSpecies:t('unknown')}
```
Comment (norbertschuler) [inline src/features/user/TreeMapper/components/PlantLocationPage.tsx:253]: Maybe you can explicitly use `maps:unknown` or `treemapper:unknown` here.

**Review by norbertschuler — CHANGES_REQUESTED** [review]
Does not work for me yet.

File: src/features/user/TreeMapper/components/PlantLocationPage.tsx (hunk 2 above)
Comment (norbertschuler) [reply src/features/user/TreeMapper/components/PlantLocationPage.tsx:177]: sorry, this is ok

File: src/features/user/TreeMapper/components/PlantLocationPage.tsx (hunk 3 above)
Comment (norbertschuler) [reply src/features/user/TreeMapper/components/PlantLocationPage.tsx:253]: this should also be ok as also other resources are not using the prefix `treemapper:`

**Review by norbertschuler — APPROVED** [review]
LGFM

**Comment by norbertschuler** [comment]
- [ ] If the "Unknown" values is already part of the data, it's no more possible to replace it with another translation. I wonder if this is a result of wrong data for myself created by an older version of the TreeMapper app or if this is still happening on production:

Bildschirmfoto 2021-09-13 um 16 32 31
